steps:
  - command: cd baserepo && docker buildx build -t image .
    key: buildx
  - command: docker image prune -f
    depends_on: buildx
    key: imageprune
  - command: docker buildx prune -f
    depends_on: imageprune
